
* Overview
This is the step-by-step guide to setting up my window manager and toolset

* Setting up Awesome Window Manager
This setup includes steps for doom emacs, but you can safely skip those if you don't use it.

** Install dependencies
- awesomewm
- compton
- nitrogen
- xfce4-terminal
- arandr

Assuming you're on debian and already have emacs:
#+BEGIN_SRC bash :tangle setup_configs.sh

# Install required dependencies
sudo nala install awesome compton nitrogen xfce4-terminal rofi arandr

#+END_SRC

If you don't use [[https://github.com/volitank/nala][nala]], then you should consider using it. It's pretty great.
But if you can't, apt will work just fine.

[[https://github.com/haad/arandr][arandr]] isn't required but it's an easy way to fix display issues.

If you don't use emacs, set =$EDITOR= in your shell config to have it open things in your favorite editor.

** Collect Dotfiles from this repo
- ~/.config/awesome/rc.lua
- ~/.config/awesome/theme.lua
- ~/.config/rofi/config.rasi
- ~/.config/xfce4/terminal/terminalrc

During the download process, it will copy any existing config files with an =.old= extension, so that you can recover any configs that would have been overwritten.

#+BEGIN_SRC bash :tangle setup_configs.sh

# Download and install config files

[ -f ~/.config/awesome/rc.lua ] && mv ~/.config/awesome/rc.lua ~/.config/awesome/rc.lua.old
wget -P ~/.config/awesome/ https://raw.githubusercontent.com/TrialAndErrror/dotfiles/main/.config/awesome/rc.lua

[ -f ~/.config/awesome/theme.lua ] && mv ~/.config/awesome/theme.lua ~/.config/awesome/theme.lua.old
wget -P ~/.config/awesome/ https://raw.githubusetheme.com/TrialAndErrror/dotfiles/main/.config/awesome/theme.lua

[ -f ~/.config/rofi/config.rasi ] && mv ~/.config/rofi/config.rasi ~/.config/rofi/config.rasi.old
wget -P ~/.config/rofi/ https://raw.githubusercontent.com/TrialAndErrror/dotfiles/main/.config/rofi/config.rasi

[ -f ~/.config/xfce4/terminal/terminalrc ] && mv ~/.config/xfce4/terminal/terminalrc ~/.config/xfce4/terminal/terminalrc.old
wget -P ~/.config/xfce4/terminal https://raw.githubusercontent.com/TrialAndErrror/dotfiles/main/.config/xfce4/terminal/terminalrc

#+END_SRC

These commands are included in the `setup_config.sh` script. If you can run that from start to finish without errors, then congrats! You're done. Now restart the machine and switch your desktop environment to the "Awesome" desktop environment and
** Optional Extras

*** Setup applications
Included in this repo is a shell script for installing common applications. Some of them have preconfigured shortcuts, while others are just nice to have. If you don't want to install non-FOSS software, change the included variable to skip installing them.

These will all be installed into your active nix profile. If you don't have nix set up, I recommend the Zero-to-Nix quick-start guide here: https://zero-to-nix.com/start/install. Their tutorial will get you up and running in minutes.

#+BEGIN_SRC bash :tangle setup_applications.sh
#!/bin/bash

INSTALL_UNFREE=1

# Devtools

echo "Installing file system tools..."
nix profile install nixpkgs#bat nixpkgs#fd nixpkgs#eza nixpkgs#pipenv

echo "Installing utilities"
nix profile install nixpkgs#mu nixpkgs#dua nixpkgs#nushell

echo "Installing formatters and linters"
nix profile install nixpkgs#nixfmt-classic nixpkgs#isort nixpkgs#python311Packages.pytest nixpkgs#python311Packages.nose


echo "Installing version control tools"
nix profile install nixpkgs#gh nixpkgs#jujutsu

# Applications
[ -n "$INSTALL_UNFREE" ] && export NIXPKGS_ALLOW_UNFREE=1 && nix profile install --impure nixpkgs#jetbrains.pycharm-professional nixpkgs#jetbrains.datagrip nixpkgs#gitkraken
#+END_SRC

*** Setup emacs transparency
In order to prettify your doom emacs:
- =(add-to-list 'default-frame-alist '(alpha . 90))= added to your doom emacs =config.el= will do the trick
  - Alternatively, =(setq default-frame-alist '((alpha . 90)))= seems to work.
- =(scroll-bar-mode -1)= to get rid of that obtrusive scroll bar

If you run into issues, check that compton is working properly; that's what we're using for a compositor.
https://github.com/chjj/compton

*** Add Themes
Check out the cool themes over at [[https://github.com/newmanls/rofi-themes-collection][rofi-themes-collection]]

** Usage
Everything you should need to tinker with start from rc.lua. The main changes I made were to keybindings and padding. Be sure to look at the added sections at the bottom for autostart applications and layout config.

If you're not familiar with awesomewm, just hit super + s to get contextual keyboard shortcuts.
