
* Overview
It's a dotfiles repo, so it's got dotfiles in it.

* Setting up Awesome Window Manager
This setup includes steps for doom emacs, but you can safely skip those if you don't use it.

** Install dependencies
- awesomewm
- compton
- nitrogen
- xfce4-terminal
- arandr

Assuming you're on debian and already have emacs:
#+BEGIN_SRC bash
sudo nala install awesome compton nitrogen xfce4-terminal rofi arandr
#+END_SRC

If you don't use [[https://github.com/volitank/nala][nala]], then you should consider using it. It's pretty great.
But if you can't, apt should work just fine for these.

[[https://github.com/haad/arandr][arandr]] isn't required but it's an easy way to fix display issues.

If you don't use emacs, set =$EDITOR= in your shell config to have it open things in your favorite editor.

** Collect Dotfiles from this repo
- ~/.config/awesome/rc.lua
- ~/.config/rofi/config.rasi
- ~/.config/xfce4/terminal/terminalrc

Example:
#+BEGIN_SRC bash
wget -P ~/.config/awesome/ https://raw.githubusercontent.com/TrialAndErrror/dotfiles/main/.config/awesome/rc.lua
wget -P ~/.config/rofi/ https://raw.githubusercontent.com/TrialAndErrror/dotfiles/main/.config/rofi/config.rasi
wget -P ~/.config/xfce4/terminal https://raw.githubusercontent.com/TrialAndErrror/dotfiles/main/.config/xfce4/terminal/terminalrc
#+END_SRC

=terminalrc= just has one extra setting for removing scrollbars from the terminal.
=rofi= controls the run menu

** Setup
*** Download [[https://github.com/newmanls/rofi-themes-collection][rofi themes]] and copy them to ~/.local/share/rofi/themes

The default theme comes from the rofi-themes-collection, so you either need to download the theme or remove the reference in config.rasi.
Don't forget to use rofi-theme-selector for quick access to changing out themes.

#+BEGIN_SRC bash
git clone https://github.com/lr-tech/rofi-themes-collection.git
mkdir -p ~/.local/share/rofi/themes/
cp rofi-themes-collection/themes/* ~/.local/share/rofi/themes/
#+END_SRC


*** Setup emacs transparency
=(add-to-list 'default-frame-alist '(alpha . 90))= added to your doom emacs =config.el= will do the trick


** Usage
Everything you should need to tinker with start from rc.lua. The main changes I made were to keybindings and padding. Be sure to look at the added sections at the bottom for autostart applications and layout config.

If you're not familiar with awesomewm, just hit super + s to get contextual keyboard shortcuts.

I manually set up terminal transparency in the Preferences section of my xfce4-terminal;
feel free to put up a PR if you have a suggestion for a config file that would handle that by default.
