* Overview
It's a dotfiles repo, so it's got dotfiles in it.

* Setting up Awesome Window Manager
** Install dependencies
- awesomewm
- compton
- nitrogen
- emacs + emacsclient
- xfce4-terminal
- arandr

Assuming you're on debian and already have emacs:
#+BEGIN_SRC bash
sudo nala install awesome compton nitrogen xfce4-terminal rofi arandr
#+END_SRC

If you don't use [[https://github.com/volitank/nala][nala]], then you should consider using it. It's pretty great.
But if you can't, apt should work just fine for these.

[[https://github.com/haad/arandr][arandr]] isn't required but it's an easy way to fix display issues.

If you don't use emacs, set =$EDITOR= in your shell config to have it open things in your favorite editor.

** Collect Dotfiles from this repo
- ~/.config/awesome/rc.lua
- ~/.config/rofi/config.rasi

Example:
#+BEGIN_SRC bash
wget -P ~/.config/awesome/ https://raw.githubusercontent.com/TrialAndErrror/dotfiles/main/.config/awesome/rc.lua
wget -P ~/.config/rofi/ https://raw.githubusercontent.com/TrialAndErrror/dotfiles/main/.config/rofi/config.rasi
#+END_SRC

** Setup
- Download [[https://github.com/newmanls/rofi-themes-collection][rofi themes]] and copy them to ~/.local/share/rofi/themes

The default theme comes from the rofi-themes-collection, so you either need to download the theme or remove the reference in config.rasi.
Don't forget to use rofi-theme-selector for quick access to changing out themes.

#+BEGIN_SRC bash
git clone https://github.com/lr-tech/rofi-themes-collection.git
mkdir -p ~/.local/share/rofi/themes/
cp rofi-themes-collection/themes/* ~/.local/share/rofi/themes/
#+END_SRC

** Usage
Everything you need is in rc.lua, the main changes I made were to keybindings and padding. Be sure to look at the added sections at the bottom for autostart applications and layout config.
